### PR TITLE
[WIP] Add docs for more components (extending Mautic)

### PR DESCRIPTION
**Pull request by dennisameling**
Builds upon #26 - please merge that one first

<a href="https://gitpod.io/#https://github.com/mautic/developer-documentation-new/pull/28"></a>

### CODE REVIEW

**Comment by dennisameling** [comment]
@RCheesley I'll update this PR latest by Sunday to at least get it into a reviewable state. Keep you posted!

**Comment by RCheesley** [comment]
Great - I have created issues for each part that needs the docs and a few have open PRs, so worth having a look at those first! :)

**Comment by dennisameling** [comment]
Will close this PR soon:
- All the `integrations`-related docs have been ported by Rahul in https://github.com/mautic/developer-documentation-new/pull/76 (Mautic 4) and https://github.com/mautic/developer-documentation-new/pull/77 (Mautic 5)
- I'll move the `forms`-related docs in this PR into a standalone PR, so that I can tackle https://github.com/mautic/developer-documentation-new/issues/61 at once.

**Comment by dennisameling** [comment]
Closing in favor of the PRs mentioned above and https://github.com/mautic/developer-documentation-new/pull/86

**Pull request closed without merging**
