### PR TITLE
Campaign docs

### PR DESCRIPTION
**Pull request by alanhartless**
This contains Campaign documentation but is dependent on https://github.com/mautic/developer-documentation-new/pull/15. 

<a href="https://gitpod.io/#https://github.com/mautic/developer-documentation-new/pull/17"></a>

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
Good to go from my perspective - would appreciate a technical review from a developer - you can open in Gitpod and open the file, then click the preview to see how it will be laid out on the docs.

**Review by escopecz — APPROVED** [review]
Reads good to me 👍

**Comment by RCheesley** [comment]
Yay we have some Vale warnings to check - will look later!

**Comment by RCheesley** [comment]
I have just pushed a commit to fix the Vale errors and most of the warnings (some are not relevant) so we are good to go now we have reviews and the linters are passing 🎉

**Pull request merged**
