### PR TITLE
Adding M5 autowiring docs

### PR DESCRIPTION
**Pull request by escopecz**
This is documenting changes in https://github.com/mautic/mautic/pull/11587

I did some more changes in https://github.com/mautic/mautic/pull/11774 to get some special cases documented in the doc

I wrote it in Markdown and then used automatic online converter tool to RST as I'm not yet very familiar with this format. I hope it's OK.

I did not want to duplicate Symofny docs too much so this article should give some basic overview and the Symfony docs are for the details.

<a href="https://gitpod.io/#https://github.com/mautic/developer-documentation-new/pull/89"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
I'm discouraged to write any docs since Wale was implemented. I don't know how to change it to comply with this tool. I don't know what is OK ignore and what is not. I think that not one warning nor error make sense. I'm going to just ignore it all and let someone who knows how to change the text to comply with Wale to suggest changes.

**Review by RCheesley — COMMENTED** [review]
Thanks for making the PR for these changes @escopecz !

Just like developers have to learn how to use the Mautic code style, and learn how write tests to improve quality and so forth, we have a [defined style](https://developers.google.com/style) for the documentation and a standard we are applying (which is an industry standard) - it does take a bit of learning, and the Vale linter is there to help with that by providing feedback on what is failing / what might need attention. 

It should give you the hints as you are typing in VSCode if you've pulled the repo down with the recommended extensions installed - happy to help walk through that if it is helpful, or you can just review it on Gitpod once you make a PR as it's all set up and ready to go there!

The Markdown to RST convertors are a good starting point but they are not great as they don't take into account some things like how we use the external links extension for example, and the headings markup we use.

I appreciate it takes time to learn something new, but this is the only way we will improve the quality and have a standardised approach to our documentation. We do need to document how to write the documentation which is something on my plate to get finished off!

As regards this PR:

- I have addressed the errors which were preventing the build of the docs. There was a warning telling you that you had not added the page to the index.rst therefore it was not in the navigation - this was preventing the preview showing on Gitpod.  

- I have also fixed the typos that Vale flagged up, and added the various versions of autowire/s/d/ing to our Mautic-specific vocabulary so that it doesn't see it as a spelling mistake.

- Grammar wise, don't use the second person (we) - [instead use You](https://developers.google.com/style/person).

- To create an [external link](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#use-the-external-links-extension) you can create the link using the built-in tool like this:

`cd docs` into the /docs folder
type `make link`
follow the steps and copy the `:xref:` path that it generates - use this in the text and it will create the link for you.

This uses the external links extension which allows us to automatically check all links are working in our GitHub Actions, and also prevents us having multiple places where links have to be updated. All existing links are in the /links directory.

- When linking to GitHub resources / files, please always use HEAD rather than a branch reference - for example:

https://github.com/mautic/mautic/blob/5.x/app/bundles/CoreBundle/DependencyInjection/MauticCoreExtension.php#L12

becomes:

https://github.com/mautic/mautic/blob/HEAD/app/bundles/CoreBundle/DependencyInjection/MauticCoreExtension.php#L12

This prevents the link breaking if a branch is removed. The exception might be if the reference is version-specific and not expected to go into a future major version - so for Symfony links I have left them using the 5.4 branch.

Hopefully this should be almost at passing the linter now with my commits! 🤞 

Thanks again for all your efforts!

**Review by RCheesley — APPROVED** [review]
The notices/info from Vale are now all ones that can be safely ignored so from my perspective this should be good to go. @dennisameling if you have a moment to glance over it from the technical perspective it would be awesome!

**Review by dennisameling — APPROVED** [review]
Wow. Thanks @escopecz!! Autowiring is such a big leap for Mautic. Really exciting to see. The docs make a lot of sense to me. Thanks again! 🎉

**Comment by escopecz** [comment]
Thank you both!

@RCheesley thanks for the comment. It explains a lot!

I did not notice that the build was failing nor any warning about `index.rst`. The Build was green. Even if I search in the output of the Prose job I don't see it. 

I understand the need for it as I implemented similar tools for the code part of this project. But the tool should either pass or not. There are many warnings from other files that I haven't touched.

But I noticed that I don't have to read the issues from the job's output which is a bit overwhelming but it's visible in the diff. I'll look there first next time.

I'm going to install Vale into VS Code now and experiment with it. Also learn how to build links.

**Comment by RCheesley** [comment]
Yeah thanks to a PR that @dennisameling made, it now shows the output in the files. The linting action is still failing - that is the one which outputs the Vale suggestions.

I will make a PR to fix the existing failures in the repo as we did not have it implemented fully to begin with I think.

**Pull request merged**
